# Use aliases rather than symlinks to ~/bin/ so that they're more cleanly source controlled.
alias zsnes='zsnes -ad sdl'
alias rm='rm -i'
alias c='clear'
alias la='ls --color=auto -a'
alias m='make'
alias mf='mv -i'
alias mv='mv -i'
alias q='exit'
alias mplayer='mplayer -osdlevel 0 -nolirc -nosub'
alias am='alsamixer -c 0'
alias play_loop='mplayer -zoom -fs -osdlevel 3 -loop 0'
alias seq='seq --format="%03g"'
alias filelight='baobab'
alias x='ssh-agent startx'
